### PR TITLE
Add launch stack validation logic

### PR DESCRIPTION
**Pull request by dragorosson**

### CODE REVIEW

**Comment by stretchservers** [comment]
Can one of the admins verify this patch?

**Comment by stretchservers** [comment]
Can one of the admins verify this patch?

**Comment by radix** [comment]
This is looking good, but it seems like there should be a new test in test_supervisor.py for the changes in supervisor.py

**Comment by dragorosson** [comment]
@radix: Done!

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
Looks good. Just gonna run the integration tests since this touches existing codepaths

**Pull request merged**
