### PR TITLE
AddNodesToCLB fails on known conditions only

### PR DESCRIPTION
**Pull request by manishtomar**
Earlier it was failing on unknown errors. This is incorrect since we should retry convergence on intermittent network failures. Now, it fails on known conditions only and return retry on any other error

### CODE REVIEW

**Comment by radix** [comment]
in my convergence cycling branch, I changed `steps_to_effect` to turn any unknown error into a RETRY, that way we wouldn't have to handle this for every step. what do you think?

**Comment by manishtomar** [comment]
How does converger know which errors are known and unknown? I thought that it will use only step statuses to make decisions and error information will be for logging purpose. If converger is able to make decisions about the kind of error then steps wouldn't need to return status right? They can always raise errors.

**Comment by radix** [comment]
@manishtomar converger is only using step status.

**Comment by radix** [comment]
@manishtomar this is what I mean, the change in effecting.py: https://github.com/rackerlabs/otter/compare/dirty-groups-3...repeat-convergence#diff-807b0b5ab96b01e953fae93a368cbd8f

**Comment by radix** [comment]
after talking on slack, conclusion is: this change is good, but you don't need the `report_retry` errback, since that can be generalized up a level.

**Comment by radix** [comment]
LGTM :) +1

**Pull request merged**
