### PR TITLE
RCv3 bulk deletes are successful if there's nothing to retry

### PR DESCRIPTION
**Pull request by lvh**

### CODE REVIEW

**Comment by lvh** [comment]
I don't understand the difference between `continuous-integration/travis-ci/pr` and `continuous-integration/travis-ci/push`. The `pr` one failed, but at:

* ./otter/test/convergence/test_steps.py:792:17: W503 line break before binary operator
* ./otter/test/convergence/test_steps.py:795:17: W503 line break before binary operator

But that file doesn't have that many lines.

**Comment by lvh** [comment]
Github isn't updating this, but the build eventually worked: https://travis-ci.org/rackerlabs/otter/builds/51020180

**Comment by lvh** [comment]
jenkins please run integration tests

**Comment by lvh** [comment]
come on jankyns

**Comment by cyli** [comment]
LGTM.

**Pull request merged**
