### PR TITLE
Always make flake8diff pass

### PR DESCRIPTION
**Pull request by lvh**
This fixes the fact that there's so much lint crud right now.

### CODE REVIEW

**Comment by radix** [comment]
So I take it this is a temporary thing until more linty stuff gets fixed? How are we going about doing this? Are you focusing your lint effort on files that have outstanding PRs, or just trying to do the whole codebase?

**Comment by cyli** [comment]
I'm not sure it gets to run the "true" part?  Randomly added an extra import in some file:

    $ make flake8diff
    git diff --patch --no-prefix 0d298ba9d214d3cc098f3b6cdef2f6f68a4391dc | flake8 --diff
    ./otter/rest/application.py:5:1: F401 'popsicle' imported but unused
    ./otter/rest/application.py:5:1: I201 Missing newline before sections or imports.
    make: *** [flake8diff] Error 1
    $ echo $?
    2

**Comment by lvh** [comment]
@radix Yes, it is temporary. I'm trying to lint the whole codebase. Things that are still relevant but don't have outstanding PRs first, because fewer conflicts. I am counting on people to run make lint still -- code quality should be a collective ownership thing, and that doesn't change because our automation briefly faltered.

@cyli huh, weird. Looking.

**Comment by lvh** [comment]
@radix I created a ticket to track that, #912.

**Comment by cyli** [comment]
This definitely seems to make things succeed on my local machine.  LGTM.

**Pull request merged**
