### PR TITLE
Generic LB model (interfaces) for converger (mergable without queuing).

### PR DESCRIPTION
**Pull request by cyli**
Some generic LB model interfaces (and specific CLB interface providers) so that the converge logic can operate on general LBs (part of fixing #821).

Here is [a sketch of what planning will look like (not full changes, no tests)](https://github.com/rackerlabs/otter/blob/a70fc77f226905422eaac91d0c8412394a18273f/otter/convergence/planning.py) - mainly, look at [_remove_from_lb_with_draining](https://github.com/rackerlabs/otter/blob/a70fc77f226905422eaac91d0c8412394a18273f/otter/convergence/planning.py#L20) and [_converge_lb_state](https://github.com/rackerlabs/otter/blob/a70fc77f226905422eaac91d0c8412394a18273f/otter/convergence/planning.py#L68).  (Will be separate PRs)

There will also be specific RCv3 implementations of ILBDescription and ILBNode (the RCv3 version may not be drainable). (Again, future PRs.)

Also looking to implement `AddToLoadBalancing` etc. as a function which checks what the types are and produces the right specific steps (in future PR).  Something like:

    def AddServerToLoadBalancing(server, description):
        if isinstance(description, CLBDescription):
            return AddNodesToLoadBalancer(description.lb_id, (server.servicenet_address, description))

Naming corrections/feedback about above welcome and requested :)

### CODE REVIEW

**Comment by manishtomar** [comment]
> Another review question - luckily CLBDescription and LBConfig are pretty similar - wondering if we should decouple the object from the AddNodeToCLB step though, since who knows if it may need change again in the future.

I thought `LBConfig` will be replaced by `CLBDescription`. If so, then `AddnodeToCLB` should take `CLBDescription` in `address_config`.

**Comment by cyli** [comment]
@manishtomar Yes, it will (see https://github.com/rackerlabs/otter/compare/generic_lb_models...use_generic_lb_models), it does take CLBDescription.  I'm just thinking if it this changes in the future.  I guess there's no hurry to make that change.

**Comment by cyli** [comment]
To clarify the above discussion with @manishtomar, basically I was suggesting making the step take a `dict` instead of an object.  But super unimportant, was just an idle thought.

Here is a sketch of what the RCv3 models will look like, and some of the CLB planning steps:

https://gist.github.com/cyli/0303219c930ff86cbd74

**Comment by manishtomar** [comment]
Thanks for the gist @cyli . This LGTM :)

**Comment by manishtomar** [comment]
`AddNodeToLoadBalancing` should be renamed to `AddNodeToLB` ?

**Comment by cyli** [comment]
@manishtomar Do you mean [`AddNodesToCLB` (already in master, it's the renamed CLB step)](https://github.com/rackerlabs/otter/blob/master/otter/convergence/steps.py#L80), or do you mean to just shorten the name to `AddNodeToLB`?  Mostly I left it long to distinguish it from CLB, but happy to change also.

**Comment by manishtomar** [comment]
> do you mean to just shorten the name to AddNodeToLB?

Yes. Also I wasn't clear the reason for `LoadBalacing` instead of `LoadBalancer`

**Comment by cyli** [comment]
@manishtomar Because for RCv3 they're technically load balancing pools, and not load balancers, so I wanted to denote some kind of load balancing entity.

I would like to make sure there's enough of a visual difference between `AddNodeToLB` and `AddNodesToCLB` though - how do you feel about changing `AddNodesToCLB` to `AddAddressesToCLB`?

**Comment by manishtomar** [comment]
> @manishtomar Because for RCv3 they're technically load balancing pools, and not load balancers, so I wanted to denote some kind of load balancing entity.

In that case, I would suggest `LoadBalancingEntity` since `LoadBalacing` seems more like a verb than a noun. 

> how do you feel about changing AddNodesToCLB to AddAddressesToCLB?

Sounds good.

**Pull request merged**
