### PR TITLE
DO NOT MERGE: Test edit on github link for docs

### PR DESCRIPTION
**Pull request by meker12**
Change from submit issue to edit github link to 
determine whether the link works.

### CODE REVIEW

**Comment by manishtomar** [comment]
Can one of the admins verify this patch?

**Comment by manishtomar** [comment]
Can one of the admins verify this patch?

**Comment by meker12** [comment]
@manishtomar   Did something change with the build pipeline?  Was expecting a preview of this change when I pushed the PR, but Strider doesn't seem to be working anymore.

**Comment by manishtomar** [comment]
@meker12 Sorry yes. I requested @smashwilson to temporarily disable previews due to too much noise. I can request him to enable it temporarily. 

Hey @smashwilson, could you please re-enable docs builder? I was thinking of disabling and enabling the corresponding webhook to avoid bringing you into this every time. What are your thoughts on that?

**Comment by meker12** [comment]
@manishtomar   The build was enabled again.  I haven't pushed anything, but after I do it will be added.  
We can just toggle the webhook to turn the Strider build on and off to avoid slowing down your dev PRs.  Thanks! 

I'm leaving this PR open for now. Will come back to see results of my experiment.  If you need to close it to avoid clutter, feel free.

**Comment by manishtomar** [comment]
Going to close and reopen to see if it triggers the build.

**Comment by manishtomar** [comment]
Trying closing and opening again.

**Comment by manishtomar** [comment]
@meker12 Looks like the build server is not running. Github got 502 when it called https://build.developer.rackspace.com/rackerlabs/otter/api/github/webhook.

**Comment by meker12** [comment]
@manishtomar  The build worked when you merged PR #1887. That PR has the preview link.  Not sure why it's not working on this one.

**Pull request closed without merging**
