### PR TITLE
Excise add_content_only

### PR DESCRIPTION
**Pull request by lvh**
Note that this does not yet *remove* `add_content_only`. If people feel that's appropriate, I'd be happy to do so in a different PR. All it does is remove it from the default `service_request` decorator stack.

While this changes the type of any `ServiceRequest` effect, it turns out we don't really use the results on those effects yet, so it doesn't matter. The only functions that do use the result (`_rcv3_check_bulk_delete`, `_clb_check_bulk_delete`) already assumed that it would be of the shape that this PR makes it.

### CODE REVIEW

**Comment by manishtomar** [comment]
LGTM

**Comment by lvh** [comment]
@manishtomar I checked metrics, too; just to be clear, that doesn't rely on the result type of `service_request` either, right? (Looks like it just makes it for side-effecty reasons.)

**Comment by manishtomar** [comment]
@lvh metrics uses `service_request` to fetch data and push metrics both of which are fine with default success predicate (i.e. 200 response).

**Comment by radix** [comment]
I definitely don't trust this is working... Any code that deals with responses will change, right? basically, any tests that use resolve_effect or resolve_stubs in service_request using code will need to change (and of course, all the implementation code that does anything with the response).

**Comment by manishtomar** [comment]
@radix Oh yeah. I am so sorry I didn't realize it. You are absolutely right. All the code calling `service_request` is expecting only content whereas this will give tuple. Damm.. I feel so stupid.

**Comment by lvh** [comment]
Yeah, that's what I didn't hit merge just yet ;-) Also note that this has nothing to do with `success_pred` by the way; it's about the type of the Effect.

**Comment by lvh** [comment]
All of the places `service_request` is being used right now:

```
otter/convergence/gathering.py
22:from otter.http import service_request
48:            service_request(
97:            service_request(

otter/convergence/steps.py
19:from otter.http import has_code, service_request
67:            return service_request(
87:        return service_request(
106:        return service_request(
178:        return service_request(
214:        eff = service_request(
269:        return service_request(
292:    return service_request(

otter/http.py
32:    def service_request(*args, **kwargs):
42:    return service_request
45:def service_request(
126:def concretize_service_request(
129:        service_request):
143:    if service_request.log is not None:
144:        log = service_request.log
146:    service_config = service_configs[service_request.service_type]
153:            invalidate_eff, service_request.reauth_codes, request_)
157:        if service_request.json_response:
160:            service_request.success_pred, request_)
163:            service_request.method,
164:            service_request.url,
165:            headers=service_request.headers,
166:            data=service_request.data,
174:        _concretize=concretize_service_request):
186:    def scoped_performer(dispatcher, service_request):
189:            tenant_scope.tenant_id, service_request)

otter/metrics.py
34:from otter.http import TenantScope, service_request
220:    return service_request(ServiceType.CLOUD_METRICS_INGEST,

otter/test/convergence/test_composition.py
22:from otter.http import service_request
165:        expected_req = service_request(

otter/test/convergence/test_gathering.py
30:from otter.http import service_request
49:    expected_eff = service_request(

otter/test/convergence/test_steps.py
26:from otter.http import has_code, service_request
48:            service_request(
68:            service_request(
82:            service_request(
97:            service_request(
116:            service_request(
139:            service_request(
227:            service_request(
315:            service_request(
506:        expected_intent = service_request(

otter/test/test_http.py
23:    concretize_service_request,
25:    service_request)
59:    """Tests for :func:`service_request`."""
62:        eff = service_request(ServiceType.CLOUD_SERVERS, 'GET', 'foo')
83:    """Tests for :func:`concretize_service_request`."""
93:        eff = service_request(ServiceType.CLOUD_SERVERS, 'GET', 'servers')
98:        Call :func:`concretize_service_request` with premade test objects.
100:        return concretize_service_request(
136:        svcreq = service_request(ServiceType.CLOUD_SERVERS, "GET", "servers",
154:        svcreq = service_request(ServiceType.CLOUD_SERVERS, "GET", "servers",
191:    def test_perform_service_request(self):
195:        :obj:`Request` as per :func:`concretize_service_request`.
197:        ereq = service_request(ServiceType.CLOUD_SERVERS, 'GET', 'servers')
210:        ereq = service_request(ServiceType.CLOUD_SERVERS, 'GET', 'servers')
```

**Comment by radix** [comment]
jenkins run integration tests please

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by lvh** [comment]
jenkins please run integration tests

**Comment by lvh** [comment]
jenkins please run integration tests

**Comment by lvh** [comment]
jenkins please run integration tests

**Comment by lvh** [comment]
All of the RCv3 tests are still failing, and taking a long time in doing so, unfortunately.

Here's the exception:

```
Traceback (most recent call last):
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 578, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/otter/models/cass.py", line 616, in wrapper
    d.addCallback(lambda ts: func(ts, *args))
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 307, in addCallback
    callbackKeywords=kw)
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 296, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 578, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/otter/models/cass.py", line 616, in <lambda>
    d.addCallback(lambda ts: func(ts, *args))
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/otter/models/cass.py", line 734, in _write_state
    'active': serialize_json_data(new_state.active, 1),
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/otter/models/cass.py", line 57, in serialize_json_data
    return json.dumps(dataOut)
  File "/usr/lib/python2.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 178, in default
    raise TypeError(repr(o) + " is not JSON serializable")
exceptions.TypeError: <treq.response._Response object at 0xc5961d0> is not JSON serializable
```

So, the most obvious thing is that the response object isn't getting thrown away, although I'm pretty sure I'm [destructuring it](https://github.com/rackerlabs/otter/pull/1023/files#diff-0353e9945cd84ab9a6f5f8629d98e04aR37)... Alas, not the most useful traceback. I'll try to get it to fail in my dev vm so I can step through it.

**Comment by lvh** [comment]
Also the relevant unit test definitely looks like it's doing the right thing.

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
@lvh: So, I think there is some kind of old state remaining in the test environment, because every single test run since this was first run has failed with the same error.  I'm not sure why, since it seems like the scripts and recipes all do the right thing - debugging it now.

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
Ok, so this passed after I manually cleared out all the old tarballs, the virtualenv, and the wheels.

Problem is that I've previously cleared out the virtualenv to no avail, and cleared out the wheels to no avail, but apparently clearing out all the tarballs helped?  I'm not sure why, since we untar the exact one that gets shipped over every time.  :|

Anyway, CI seems to pass now.

**Comment by cyli** [comment]
@radix has figured it out - the otter process doesn't get stopped/restarted (which is in the cleanup process of the jenkins job) if the tests fail.  Fixed now.

**Comment by radix** [comment]
LGTM! merging.

**Pull request merged**
