### PR TITLE
moved cloud_client CLB functions to clb.py

### PR DESCRIPTION
**Pull request by manishtomar**
And changed all the callers to point to the new place. This will help in refactoring another PR I've in mind to split out reading feeds as a generic function. Sorry this is too long but be ensured this is pure refactor.

### CODE REVIEW

**Comment by manishtomar** [comment]
jenkins please run integration tests

**Comment by manishtomar** [comment]
jenkins please run integration tests

**Comment by manishtomar** [comment]
jenkins please run integration tests

**Comment by manishtomar** [comment]
jenkins please run integration tests

**Comment by manishtomar** [comment]
@glyph review please

**Comment by glyph** [comment]
Taking it on faith that there's not much here besides moves (the diff is really big) this generally looks like an improvement; a more sensibly namespaced client codebase.  Land away.

**Pull request merged**
