### PR TITLE
Test self-healing on disowned servers

### LINKED ISSUE #1486: Load balancers used in ... 1 group, 2 servers, LB1 on group, LB2 not on group
Load balancers used in autoscale configureations MAY have non-autoscale servers on them and Convergence SHALL only clean up servers managed by autoscale.

(This test is largely covered by the others, but it is straightforward and can also be applied to RCV3 so I would advocate including it anyway.)

1 group, 2 servers, LB1 on group, LB2 not on group

Disown 1 server
Move disowned server to LB2
Trigger convergence:
Assert: moved server is not moved back to LB1

### LINKED ISSUE #1487: Load balancers used in ... 1 group, n servers, LB1 on group, LB2 not on group (read description)
Load balancers used in autoscale configureations MAY have non-autoscale servers on them and Convergence SHALL only clean up servers managed by autoscale.

(This test is largely covered by the others, but it is straightforward and can also be applied to RCV3 so I would advocate including it anyway.)

1 group, n servers, LB1 on group, LB2 not on group

Disown 1 server
Add disowned server to LB2 as well as LB1
Trigger convergence:
Assert: Disowned server is on both LB1 and LB2

### PR DESCRIPTION
**Pull request by cyli**
These tests do not pass due to #1698.

I have a fix for that issue, which does cause these tests to pass.

Fixes #1486.
Fixes #1487.

### CODE REVIEW

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by manishtomar** [comment]
Shouldn't the cafe tests running on convergence tenants have caught this?

**Comment by cyli** [comment]
@manishtomar I though to so too, but our cafe tests only seem to test the case where `purge=True`

**Comment by cyli** [comment]
@manishtomar found https://github.com/rackerlabs/otter/issues/764 relating to this.

I think this issue also fixes #764.

**Comment by radix** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[otter/integration/tests/test_lbsh.py, line 372 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1699#-JyK8osTNMWCAF7ds7AI)** ([raw file](https://github.com/rackerlabs/otter/blob/10c232fd603240d2bdeb6687acb30672818c0117/otter/integration/tests/test_lbsh.py#L372)):</sup>
I think this needs to be removed because #1698 is fixed now?

---

<sup>**[otter/integration/tests/test_lbsh.py, line 424 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1699#-JyK8r3R7Q_VM-qcYSxR)** ([raw file](https://github.com/rackerlabs/otter/blob/10c232fd603240d2bdeb6687acb30672818c0117/otter/integration/tests/test_lbsh.py#L424)):</sup>
Likewise

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rackerlabs/otter/1699)

**Comment by radix** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rackerlabs/otter/1699)

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
LGTM!

---

Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rackerlabs/otter/1699)

**Pull request merged**
