### PR TITLE
Project updates per legal and prod mgmt

### PR DESCRIPTION
**Pull request by meker12**
Remove pricing and SLA content per product mgmt
Add disclaimer.

### CODE REVIEW

**Comment by manishtomar** [comment]
Can one of the admins verify this patch?

**Comment by manishtomar** [comment]
Can one of the admins verify this patch?

**Comment by manishtomar** [comment]
LGTM. Although I wonder what is the correct place to put pricing info?

**Comment by meker12** [comment]
https://www.rackspace.com/cloud/auto-scale  -- Free when you sign up for a Cloud account.  

Cloud Pricing info is here: https://www.rackspace.com/cloud/public-pricing

**Pull request merged**
