### PR TITLE
Add a CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by radix**
This formalizes our review process and some other bits of process.

### CODE REVIEW

**Comment by radix** [comment]
@manishtomar: since you haven't yet responded on the mailing list, can I get a specific review from you (as well as anyone else who wants to review this :))

**Comment by radix** [comment]
Input from @sam-falvo, @kivattik, and @MariaAbrahms would also be appreciated, as this document makes (very light) reference to documentation and testing procedures.

**Comment by lvh** [comment]
LGTM! Only thought is re: In Progress label vs just closing the PR if it's not open for review/merging?

**Comment by manishtomar** [comment]
Sorry for not responding earlier. I actually like the review tag. It makes it very clear that a PR is up for review. Its good that the tag is not automatically assigned but will be nice that the author can add it later when they think it is ready for review.

**Comment by lvh** [comment]
I would prefer to not have 1 bit (open/closed) + 1 bit (review tag, no review tag) + 1 bit (in progress tag, no in progress tag) so we can encode 1 bit of information. Otherwise, we have a bunch of inconsistent states that probably mean something very different to a random passer-by than they formally do according to the development standard.

**Comment by radix** [comment]
@manishtomar well, we already use an "in progress" label, so we're not getting any additional information out of the "review" label -- I think it's clear that we only need one or the other. My argument for getting rid of "review" and keeping "in progress" is that "in progress" is the uncommon case, so it's less of a process burden to require people to explicitly add "in progress" when they don't want it to be reviewed yet.

**Comment by radix** [comment]
@lvh I hadn't thought of closing PRs. I wonder how well that works in practice... 

I remember that some of the Twisted developers discussed it when considering how to translate the Twisted review process to GitHub, and the conclusion was that it was a bad idea because it can seem like an aggressively negative thing to a third-party contributor. However, that may not be a concern for us, since third-party contributors to Otter are extremely rare (I can't say "non-existent", thanks to @tomprince :)

**Comment by lvh** [comment]
Yeah. It's not terribly common, even though it's supposedly the canonical Github thing to do. I guess we could leave a friendly message? One of the issues is that people without commit access can not re-open PRs. As a result, I'm also willing to accept a single tag. I agree with @radix reasoning to use in progress; also because when I open a PR to a project on Github, I don't expect to have to do more stuff for that to mean "please look at my PR".

Then, the encoding works like:

- open, not in progress: ready for review
- open, in progress: open, but don't bother looking
- closed, not in progress: retracted/closed as invalid
- closed, in progress: invalid state, probably shouldn't happen

**Comment by manishtomar** [comment]
Sounds good about "in progress". LGTM

**Comment by radix** [comment]
Thanks @manishtomar and @lvh.

Since it's relevant to this very PR, I've added some words about what to do when a conversation or disagreement erupts on a PR. Please check out the most recent change.

**Comment by lvh** [comment]
LGTM!

**Comment by manishtomar** [comment]
LGTM about disagreement.

**Comment by radix** [comment]
I just added a line about reviewers being able to merge a PR. That was one of my main goals with this doc but I forgot to spell it out.

**Comment by lvh** [comment]
Still LGTM :)

**Comment by sam-falvo** [comment]
LGTM as well.  I'd like to steal this for my Kestrel's repo.

**Comment by radix** [comment]
Alright, this has had enough eyeballs for now. If anyone else things something should change, submit a PR :)

**Pull request merged**
