### PR TITLE
Refactor cloud client a little

### PR DESCRIPTION
**Pull request by cyli**
To prepare for changes coming in #1512 and #1510

### CODE REVIEW

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
pip issue due to two builds at once.  trying again.

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
Very nice cleanup :)

**Pull request merged**
