### PR TITLE
Makefile improvements for building documentation

### PR DESCRIPTION
**Pull request by lvh**
This also moves more behavior into the Makefile so that Jenkins can leverage it effectively, while having as little behavior as possible living in Jenkins.

### CODE REVIEW

**Comment by cyli** [comment]
retest this please
(Changed jenkins to no longer run maven manually and just call make docbook.)

**Comment by lvh** [comment]
Oh, docs doesn't build the docbook target yet. Oops.

**Comment by cyli** [comment]
@lvh Actually if we build them separately we can have separate step plots on jenkins.  Although I could always make it do sphinxdoc and then docbook separately.

**Comment by cyli** [comment]
retest this please

**Comment by lvh** [comment]
Sure, they're still available as separate build targets if you'd like. That said, `make docs` should build all the docs, right? Also, Jenkins only appears to call `make docs` right now, so previously that only did Sphinx.

**Comment by cyli** [comment]
@lvh sure :)

**Comment by cyli** [comment]
LGTM!

**Pull request merged**
