### PR TITLE
Finish converting all the hard-coding of URL and service catalog keys

### PR DESCRIPTION
**Pull request by cyli**
In the integration tests, so we can include these tests in jenkins.

### CODE REVIEW

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by sam-falvo** [comment]
I totally look good.  I mean, this totally looks good.  +1!

**Pull request merged**
