### PR TITLE
Tests for autoscale self-healing changes in CLB params

### LINKED ISSUE #1241: CLBChangeNode should retry on "loadBalancerFault" (400, 500)
Relevant documentation: http://docs.rackspace.com/loadbalancers/api/v1.0/clb-devguide/content/PUT_updateNode_v1.0__account__loadbalancers__loadBalancerId__nodes__nodeId__Nodes-d1e2173.html#PUT_updateNode_v1.0__account__loadbalancers__loadBalancerId__nodes__nodeId__Nodes-d1e2173-Request

### LINKED ISSUE #1242: CLBChangeNode should retry on 503 Service Unavailable
Relevant docs: http://docs.rackspace.com/loadbalancers/api/v1.0/clb-devguide/content/PUT_updateNode_v1.0__account__loadbalancers__loadBalancerId__nodes__nodeId__Nodes-d1e2173.html#PUT_updateNode_v1.0__account__loadbalancers__loadBalancerId__nodes__nodeId__Nodes-d1e2173-Request

### LINKED ISSUE #1243: CLBChangeNode should fail on 400
*Except* that the [relevant documentation](http://docs.rackspace.com/loadbalancers/api/v1.0/clb-devguide/content/PUT_updateNode_v1.0__account__loadbalancers__loadBalancerId__nodes__nodeId__Nodes-d1e2173.html#PUT_updateNode_v1.0__account__loadbalancers__loadBalancerId__nodes__nodeId__Nodes-d1e2173-Request) that 400 can also happen on (ostensibly transient) load balancer faults. On the one hand, we need to eventually stop retrying if something is really wedged, on the other, we don't want to wedge a group because CLB accidentally threw a 400 when it meant 500.

### LINKED ISSUE #1267: Converte ChangeCLBNode to use cloud_client.change_clb_node
It should probably return (StepResults.SUCESS, []), on success, but I guess just let all the other errors bubble up, since that would cause a retry?  I'm not sure if anything should be an absolute FAILURE.

### LINKED ISSUE #1491: Tests that convergence will make sure autoscaled servers ... 1 Scaling group on 1 CLB with other non-autoscale nodes
Tests that convergence will make sure autoscaled servers put CLB nodes back in the state they should be in:

1 Scaling group on 1 CLB with other non-autoscale nodes
Change 1 server’s CLB node status
from ENABLED to DRAINING
from weight 1 to 2
from PRIMARY to SECONDARY
Trigger convergence
Assert: all autoscaled servers should be in ENABLED mode, weight 1, PRIMARY

### PR DESCRIPTION
**Pull request by cyli**
This was originally just an integration tests that fixes #1491.

However, found a bug where we were not passing the right payload to CLB - we were passing something like `{"weight": 1, "condition": "ENABLED"}` instead of `{"node": {"weight": 1, "condition": "ENABLED", "type": "PRIMARY"}}`.

So changed that in `cloud_client`, but that also required a change to `steps`.

Fixes #1241.
Fixes #1242.
Fixes #1243.
Fixes #1267.

This makes `ChangeCLBNode` fail if the CLB has been deleted, but maybe that is not always the desired outcome.  See #1705.

[Review on Reviewable](https://reviewable.io/reviews/rackerlabs/otter/1704)

### CODE REVIEW

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
I've merged the branch forward.

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[otter/convergence/steps.py, line 321 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1704#-JyNssWlag2Vtr6g4mr3)** ([raw file](https://github.com/rackerlabs/otter/blob/76c17f7bbb054776d038c12856d7070ec8444d4b/otter/convergence/steps.py#L321)):</sup>
Huh! I didn't realize we weren't using our existing `change_clb_node` function! thanks for fixing this :)

---

<sup>**[otter/convergence/steps.py, line 326 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1704#-JyNxG5b7PK4bcBzw4mB)** ([raw file](https://github.com/rackerlabs/otter/blob/d5f0c14788c6b6843b805a8434858f52dabc8d5e/otter/convergence/steps.py#L326)):</sup>
Oh, and it looks like this is another important change.

---

<sup>**[otter/test/convergence/test_steps.py, line 383 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1704#-JyNyxLzZ_iIOpXikro4)** ([raw file](https://github.com/rackerlabs/otter/blob/d5f0c14788c6b6843b805a8434858f52dabc8d5e/otter/test/convergence/test_steps.py#L383)):</sup>
I think I'd like to see this test split up into three -- success, terminal errors, and nonterminal errors. I can take care of that :) 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rackerlabs/otter/1704)

**Comment by radix** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rackerlabs/otter/1704)

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by manishtomar** [comment]
jenkins please run integration tests

**Comment by manishtomar** [comment]
Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[otter/cloud_client.py, line 599 \[r1\]](https://reviewable.io:443/reviews/rackerlabs/otter/1704#-JyLwVjmiHu5LRIfMStj)** ([raw file](https://github.com/rackerlabs/otter/blob/16f4885987a89076627bdae2b42ee139491f24db/otter/cloud_client.py#L599)):</sup>
:( Looks like this code was never exercised in any integration test. Thanks for doing this @cyli.

---

<sup>**[otter/convergence/steps.py, line 330 \[r4\]](https://reviewable.io:443/reviews/rackerlabs/otter/1704#-JyP5lWatHUrq13IHm16)** ([raw file](https://github.com/rackerlabs/otter/blob/eb0cb9275d5ace0a1c521baad0de4276144cab92/otter/convergence/steps.py#L330)):</sup>
Shouldn't `CLBNotActiveError` be transient? I am guessing CLB will become ACTIVE after sometime.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rackerlabs/otter/1704)

**Comment by manishtomar** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by manishtomar** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
Welp, it passed :)

**Comment by manishtomar** [comment]
@radix Is this good to go? If so, please merge it :)

**Pull request merged**
