### PR TITLE
Rename otter.http to otter.cloud_client

### PR DESCRIPTION
**Pull request by cyli**
As per discussion with @manishtomar and @radix last week, rename `otter.http`

As per discussion with @radix on slack, rename it to `otter.cloud_client`

### CODE REVIEW

**Comment by radix** [comment]
LGTM if the build passes :)

**Comment by cyli** [comment]
jenkins please run unit tests

**Comment by cyli** [comment]
jenkins please run unit tests

**Comment by cyli** [comment]
jenkins please run unit tests

**Comment by manishtomar** [comment]
`cloud_client` seems hipster(y) (due to the "cloud" buzzword) but its an accurate name :)

LGTM!

**Comment by radix** [comment]
@manishtomar fwiw I was thinking there was an understood "Rackpace® Managed " prefixed to "Cloud" :)

**Pull request merged**
