### PR TITLE
Change IStep.as_request to IStep.as_effect, get rid of steps.Request

### LINKED ISSUE #929: Replace IStep.as_request with IStep.as_effect, to allow more flexibility in what steps can do
This will allow steps to have effects other than *just* producing a fixed, static HTTP Request. Most pressing, we need CreateServer to be able to generate a random name to put into the launch config.

### PR DESCRIPTION
**Pull request by radix**
Fixes #929.

Pretty straightforward change -- all the as_request methods have been renamed to as_effect, and they call service_request instead of instantiating a Request.

### CODE REVIEW

**Comment by manishtomar** [comment]
So, no retry in returned effects. Where do you think retries should be there?

**Comment by radix** [comment]
Well, there was no retry in the previous code, so this just maintains the same behavior. Adding retries should be in a different PR.

**Comment by manishtomar** [comment]
Sounds good :). Just wanted to clarify when and where they will be there. IMHO, the returned effects should have retry in them as they are aware of the kind request they are making and will be most equipped with kind of retry that needs to be done.

**Comment by radix** [comment]
@manishtomar oh, okay, I totally misunderstood. yeah, makes sense to do it there :)

**Comment by lvh** [comment]
retest this please

**Comment by lvh** [comment]
This LGTM if Jenkins agrees. What's the ticket for adding the retries?

**Comment by lvh** [comment]
FYI, there's two ostensibly relevant tickets:

- https://github.com/rackerlabs/otter/issues/791
- https://github.com/rackerlabs/otter/issues/805

I think #791 can stay as-is. It still makes sense for a default retry policy to exist. It's okay if that's explicit instead of an implicit kwarg, that's up to whoever owns the ticket.

#805, that's a different beast. Maybe it should be closed as invalid: you can just wrap the effects returned from as_effect with a retrying effect, right?

**Comment by manishtomar** [comment]
> Maybe it should be closed as invalid: you can just wrap the effects returned from as_effect with a retrying effect, right?

The decision on whether the effect should be retries is dependent on the Step. For example, `CreateServer` step will retry with a get server ID to ensure server is not created whereas `DeleteServer` can just retry until it gets 204. Similarly, CLB retries should account for 422 codes and such.

**Comment by radix** [comment]
Yeah, agreed. I think #805 should be marked invalid; I'll do that.

**Comment by lvh** [comment]
@radix So, is this in progress? Only because of the dependent PR, or something else?

**Comment by lvh** [comment]
(I'm asking because my RCv3 change can't start without this)

**Comment by radix** [comment]
Only because of the dependent branch. I've removed the in progress label now.

**Pull request merged**
