### PR TITLE
Upgrade Twisted to 15.0.0

### PR DESCRIPTION
**Pull request by lvh**
Thanks, @hawkowl!

### CODE REVIEW

**Comment by hawkowl** [comment]
There's also Klein 15.0, by the way! :)

**Comment by hawkowl** [comment]
There's also Klein 15.0, by the way! :)

**Comment by lvh** [comment]
Yeah but there's also https://github.com/rackerlabs/otter/issues/889 :(

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by lvh** [comment]
What the heck? These failures don't even seem to have anything to do with twisted...

```

======================================================================
ERROR: test_system_launchconfig_without_server_name (test_repo.autoscale.system.group.test_system_launch_config.LaunchConfigTest)
Create a scaling group with a scaling policy, without server name in the launch config.         Ensure servers were created on the scaling_group.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/dev-ci-integration-tests/.cf-ve/local/lib/python2.7/site-packages/test_repo/autoscale/system/group/test_system_launch_config.py", line 171, in test_system_launchconfig_without_server_name
    self.verify_server_count_using_server_metadata(group.id, self.gc_min_entities_alt)
  File "/var/lib/jenkins/workspace/dev-ci-integration-tests/.cf-ve/local/lib/python2.7/site-packages/test_repo/autoscale/fixtures.py", line 338, in verify_server_count_using_server_metadata
    self.get_group_servers_based_on_metadata(group_id)
  File "/var/lib/jenkins/workspace/dev-ci-integration-tests/.cf-ve/local/lib/python2.7/site-packages/test_repo/autoscale/fixtures.py", line 327, in get_group_servers_based_on_metadata
    return [s for s in self.get_non_deleting_servers() if is_in_group(s)]
  File "/var/lib/jenkins/workspace/dev-ci-integration-tests/.cf-ve/local/lib/python2.7/site-packages/test_repo/autoscale/fixtures.py", line 302, in get_non_deleting_servers
    self.server_client.list_servers_with_detail(name=name).entity)
TypeError: 'NoneType' object is not iterable
```

**Comment by lvh** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
@lvh looks like there's a mimic bug preventing our integration tests from passing

**Comment by lvh** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
All the integration tests pass, logging still seems sane.  LGTM.

**Pull request merged**
