### PR TITLE
handle another completely random variation of "your LB is gone"

### LINKED ISSUE #1551: Handle 410 load balancer deleted from CLBs
Saw `APIError(code=410, body='{"message":"The loadbalancer is marked as deleted.","code":410}'` earlier.  We don't handle this currently.

### PR DESCRIPTION
**Pull request by radix**
Fixes #1551

### CODE REVIEW

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
LGTM pending +1 from jenkins  (we don't actually have an integration test for this specific case yet though - I just saw it from prod)

**Comment by cyli** [comment]
:(  will debug

**Comment by radix** [comment]
jenkins please run integration tests

**Pull request merged**
