### PR TITLE
Move _try_json_message to utils

### LINKED ISSUE #1159: Move `try_json_error` from steps to to utils
Since it might be useful for other parsing purposes.

See https://github.com/rackerlabs/otter/pull/1130#discussion_r25984699

### PR DESCRIPTION
**Pull request by cyli**
Also includes some other small changes that I will probably need later.

Fixes #1159.

### CODE REVIEW

**Comment by radix** [comment]
it looks like this needs merged forward?

**Comment by cyli** [comment]
@radix: I don't think there are any conflicts?  Will merge forward anyway though.

**Comment by radix** [comment]
sorry @cyli, I was confused about two things

1. the test_cloud_client.py rename (which is fine, I just didn't realize it was intended to be in this branch)
2. the requirements.txt change -- why'd you add six==1.9.0? I don't see any introduction of six usage. (I'm also adding six to requirements.txt in my own branch, just thought maybe some weird cross-contamination happened).

anyway neither of those things are a problem, I was just confused :)

**Comment by cyli** [comment]
@radix: "Also includes some other small changes that I will probably need later."  :)

The test change should have happened in the previous branch, it was forgotten.
Six will be needed in my next PR, I can just do it there if you prefer.

**Comment by radix** [comment]
nope this is great. +1 :)

**Pull request merged**
