### PR TITLE
Log server create response

### PR DESCRIPTION
**Pull request by cyli**
First attempt at logging responses from `cloud_client`, as per #1635.  Also associating these logs by getting the request ID put into the request in #1637.

Does this look like a good place to put the logging?

### CODE REVIEW

**Comment by cyli** [comment]
jenkisn please run integration tests

**Comment by manishtomar** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
You'll need to add an entry to spec.py for `request-create-server`. Other than that, this looks good to me :)

**Comment by radix** [comment]
(the reason this is necessary isn't just to get the fancy english-text message, but the existence of an entry in spec.py properly maps the `request-create-server` string into the `otter_msg_type` field so we can filter on it properly)

**Comment by cyli** [comment]
@radix: oh right!  thanks, I totally forgot about the filtering.  :)

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
LGTM :)

**Pull request merged**
