### PR TITLE
Add 'links' to NovaServer, and serialize them when recording to the DB

### LINKED ISSUE #1119: Active server links JSON not written to DB
Listing groups for a convergence tenant results in the following traceback:

```
Traceback (most recent call last):
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
    self._runCal
lbacks()
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 578, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/otter/.ve/local
/lib/python2.7/site-packages/twisted/internet/defer.py", line 383, in callback
    self._startRunCallbacks(result)
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 491,
 in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/opt/otter/.ve/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 578, in _runCallbacks
    current.resu
lt = callback(current.result, *args, **kw)
  File "/opt/otter/otter/rest/groups.py", line 181, in format_list
    } for state in group_states]
  File "/opt/otter/otter/rest/groups.py", line 74, in format_sta
te_dict
    } for key, server_blob in state.active.iteritems()
exceptions.KeyError: 'links'
```

Because in the DB, an example of the data stored in active servers looks like:

`{"test-server2137886081-id-2137886081": {"id": "test-server2137886081-id-2137886081"}, "test-server2913956880-id-2913956880": {"id": "test-server2913956880-id-2913956880"}}`

The worker stores a lot more info, but the only things autoscale presents to the user are the `id` and the `links`, so just making sure the links are available will probably solve this bug.

Can be solved probably as part of #1106.

This should make a bunch of functional tests pass.

### PR DESCRIPTION
**Pull request by cyli**
Fixes #1119 

Seems to eliminate the errors in the functional tests (although there are still a couple failures).

### CODE REVIEW

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by manishtomar** [comment]
Should've caught this in earlier review

**Comment by manishtomar** [comment]
LGTM :)

**Pull request merged**
