### PR TITLE
Cassandra tests lint fixes

### PR DESCRIPTION
**Pull request by lvh**
It's still complaining about import order, but I can't figure out why. There's a REVIEW comment in there... somewhere.

### CODE REVIEW

**Comment by lvh** [comment]
Oops, looks like I actually screwed up a test...

**Comment by lvh** [comment]
Okay, should be fixed now.

Remaining lint (which I don't understand...):

```
~/P/r/otter: make flake8diff                                                                                                                                                                        09:09:05
git diff --patch --no-prefix 157afd27badbd44de96bae0453012b881db5eddd | flake8 --diff
./otter/test/models/test_cass_models.py:11:1: I201 Missing newline before sections or imports.
./otter/test/models/test_cass_models.py:12:1: I201 Missing newline before sections or imports.
./otter/test/models/test_cass_models.py:13:1: I201 Missing newline before sections or imports.
./otter/test/models/test_cass_models.py:14:1: I201 Missing newline before sections or imports.
./otter/test/models/test_cass_models.py:15:1: I201 Missing newline before sections or imports.
make: *** [flake8diff] Error 1
```

**Comment by lvh** [comment]
Thanks for the help with the import lint, @radix!

**Comment by radix** [comment]
I'm reviewing this.

**Comment by radix** [comment]
+                                 # REVIEW: is ^ this actually realistic?
+                                 # Shouldn't this be an iso8601-ish timestamp?

I assume the content in there doesn't actually matter for the test - like, active and pending values also don't look like they would for real.  I don't think it's a problem. The test is just proving that it returns the same data it fetches.

You changed a bunch of cases of the integer `6` to ConsistencyLevel.TWO, but ConsistencyLevel.TWO is 7 for me. QUORUM is 6. Though I see that you changed it in both the test data and the assertion, so I guess it doesn't matter.

Why did you change all the GroupState calls to pass arguments by keyword, even though they take them positionally?

This LGTM, but for future lint-fixes I would recommend trying to minimize the changes you make to expedite review :) I won't merge in case you want to clean up some things like the "REVIEW" comment

**Comment by lvh** [comment]
> I assume the content in there doesn't actually matter for the test - like, active and pending values also don't look like they would for real.  I don't think it's a problem. The test is just proving that it returns the same data it fetches.

Possibly. Sometimes it is problematic. Consider what happened with IPs (`"ipv4"` vs an actual IP) and dates (upgrading iso8601). Both of those caused test breakage because a test used some bogus test data.

> You changed a bunch of cases of the integer `6` to ConsistencyLevel.TWO, but ConsistencyLevel.TWO is 7 for me. QUORUM is 6. Though I see that you changed it in both the test data and the assertion, so I guess it doesn't matter.

I didn't check which is which; I just wanted to use the real thing. I'm not supposed to know/care that those things are actually integers...

> Why did you change all the GroupState calls to pass arguments by keyword, even though they take them positionally?

I don't think anyone can reasonably tell the umpteen positional arguments apart when they're a bunch of (usually empty) literals.

> This LGTM, but for future lint-fixes I would recommend trying to minimize the changes you make to expedite review :) I won't merge in case you want to clean up some things like the "REVIEW" comment

Okay.

**Comment by lvh** [comment]
Thanks for reviewing this, @radix!

**Pull request merged**
