### PR TITLE
Remove get_request_func

### PR DESCRIPTION
**Pull request by radix**
This is in-progress while #936 is in review.

This deletes get_request_func and removes the last few pieces of code that called it.

In supervisor.py, I renamed request_func to request_bag (and added a RequestBag characteristic object to hold all that data).

I didn't update all the mentions of "request_func" launch_server_v1 just because I didn't want _too_ much churn...

### CODE REVIEW

**Comment by lvh** [comment]
I wonder how to get Github to generate new diffs, because this is still showing changes merged in #936, it seems.

**Comment by lvh** [comment]
Manual inspection suggests this is fine, but I kind of want Github to show me its opinion of the PR diff.

**Comment by radix** [comment]
I'll merge forward

**Comment by manishtomar** [comment]
Can RCv3 tests be run before merging this?

**Comment by lvh** [comment]
Given the apparent proximity of the RCv3 tests to master, maybe we should review that PR? It's starting to grow a beard ;)

**Comment by lvh** [comment]
retest this please

**Comment by manishtomar** [comment]
I am going to run sanity RCv3 test on it.

**Comment by manishtomar** [comment]
RCv3 test pass :). This is good to go.

**Comment by radix** [comment]
I don't actually see a "LGTM" in any PR comments, can someone confirm if it's ok to merge this? (or just merge it)

**Pull request merged**
