### PR TITLE
CLB trial tests retry on 413

### PR DESCRIPTION
**Pull request by cyli**
Handle 413 from CLB, and extend the timeouts for retrying because of transient errors.

### CODE REVIEW

**Comment by cyli** [comment]
Actually now I'm encountering intermittent network errors, so I'm thinking about just making all the tests use a retrying treq, which always retries on 413 overlimit (because all of Rackspace's cloud uses repose and produces the same request rate limiting message), and `twisted.web._newclient.ResponseNeverReceived` errors.

**Comment by radix** [comment]
@cyli  :+1:

**Comment by cyli** [comment]
Ok, closing this in favor of #1591

**Comment by cyli** [comment]
Ok, I think retrying-treq may not be working out.  :|    We may need this again.

**Pull request closed without merging**
