### PR TITLE
Nova server repr

### LINKED ISSUE #1652: Add a __repr__ for NovaServer so that not all of server_json is logged
Since we don't need most of the fields that gets returned by list server details, and fields like ID don't need to be repeated both in the model and the server JSON.  The extra fields make some log messages very long.

However, other fields like status and os task state (whichever is the one that says "deleting") and metadata are useful because they let us know if we interpreted the Nova data correctly.  

Created, updated, and name may also be useful when reporting bugs to Nova or debugging test failures.

We can also be eliminate the pmaps in the repr.

### PR DESCRIPTION
**Pull request by cyli**
Makes the NovaServer `repr` a little shorter and easier to read.
Fixes #1652.

Tested this on dev vm - the `servers` part of the execute-convergence logs now look like:

`"<NovaServer(id=u'test-server7015522524-id-7015522524', state=<ServerState=DELETED>, created=1439241282.299928, image_id=u'cca73d10-8953-4949-a2f2-1e5444a4130d', flavor_id=u'2', links=[{u'href': u'http://localhost:8900/mimicking/NovaApi-837c09/ORD/v2/000000/servers/test-server7015522524-id-7015522524', u'rel': u'self'}, {u'href': u'http://localhost:8900/mimicking/NovaApi-837c09/ORD/000000/servers/test-server7015522524-id-7015522524', u'rel': u'bookmark'}], desired_lbs=set([<CLBDescription(lb_id=u'31430', port=80, weight=1, condition=<CLBNodeCondition=ENABLED>, type=<CLBNodeType=PRIMARY>)>]), servicenet_address=u'10.180.245.166', json={u'status': u'DELETED', u'updated': u'2015-08-10T21:14:51.784378Z', u'OS-EXT-STS:task_state': None, u'name': u'6fc60544-1439241270.08-asc3dc2c16', u'metadata': {u'rax:autoscale:group:id': u'7366b343-7b1a-4f25-9979-6eabb3a98b21', u'rax:autoscale:lb:CloudLoadBalancer:31430': u'[{\"port\": 80}]', u'rax:auto_scaling_group_id': u'7366b343-7b1a-4f25-9979-6eabb3a98b21'}})>",  "<NovaServer(id=u'test-server9361275831-id-9361275831', state=<ServerState=DELETED>, created=1439241272.532468, image_id=u'cca73d10-8953-4949-a2f2-1e5444a4130d', flavor_id=u'2', links=[{u'href': u'http://localhost:8900/mimicking/NovaApi-837c09/ORD/v2/000000/servers/test-server9361275831-id-9361275831', u'rel': u'self'}, {u'href': u'http://localhost:8900/mimicking/NovaApi-837c09/ORD/000000/servers/test-server9361275831-id-9361275831', u'rel': u'bookmark'}], desired_lbs=set([<CLBDescription(lb_id=u'31430', port=80, weight=1, condition=<CLBNodeCondition=ENABLED>, type=<CLBNodeType=PRIMARY>)>]), servicenet_address=u'10.180.61.145', json={u'status': u'DELETED', u'updated': u'2015-08-10T21:14:51.783231Z', u'OS-EXT-STS:task_state': None, u'name': u'6fc60544-1439241270.08-as37fa0672', u'metadata': {u'rax:autoscale:group:id': u'7366b343-7b1a-4f25-9979-6eabb3a98b21', u'rax:autoscale:lb:CloudLoadBalancer:31430': u'[{\"port\": 80}]', u'rax:auto_scaling_group_id': u'7366b343-7b1a-4f25-9979-6eabb3a98b21'}})>"`

### CODE REVIEW

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
After seeing this printed out like that, I wonder if we should just elide the json from the NovaServer and just include the `json` manually in certain specific logs (as structured data)...

but I'm +1 on this branch regardless of that comment :) Thanks for the @attr change :)

**Comment by radix** [comment]
and the validator is super cool

**Comment by cyli** [comment]
@radix Do you mean have `execute-convergence` print out the JSON from Nova, and then also a list of NovaServers?  (I'd be happy to continue discussing here, or in a new issue, but probably just going to merge this PR and that can be a new one :D)

**Comment by radix** [comment]
@cyli yep, that's the kind of thing I meant. Maybe it's not even necessary to log the NovaServer repr in that case.

Anyway, I don't think it's important, just an idea. It'd be nice to have that stuff in the log as structured data. What do you think?

**Comment by cyli** [comment]
@radix That sounds very reasonable - And it might be nice to have an explicit "gathering results summary" in addition to the execute-convergence.

The one very minor argument I'd have against it is that it's easier to see if we synthesized statuses correct if the JSON was associated with the NovaServer - but we don't do that kind of debugging very often, and for shorter server lists, it's easy enough to correlate the two.

I think the NovaServer repr may still be useful, because that's sort of information we correlated together based on the gathering info (such as whether we're treating a server as deleted, or what CLBs we think a server is on).  It might be useful to explicitly log what the gathering step interpreted all the data as, in case a bug introduced in that logic.  But this seems more defensive than anything on my part (we do have unit tests to ensure against these bugs).

**Pull request merged**
