### PR TITLE
update to rackspace-docs-parent-1.0.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by steveortiz**

### CODE REVIEW

**Comment by stretchservers** [comment]
Can one of the admins verify this patch?

**Comment by stretchservers** [comment]
Can one of the admins verify this patch?

**Comment by manishtomar** [comment]
@steveortiz Since I don't understand docbook I am going to merge it. Did you have any more commits planned in this PR?

**Comment by meker12** [comment]
@manishtomar   You can go ahead and merge this commit.  This was the only update required for this issue.  Thanks!

**Pull request merged**
