### PR TITLE
Upgrade klein

### PR DESCRIPTION
**Pull request by lvh**
This should be done after #1071.

This doesn't work yet, but I thought it was a pretty interesting failure, which leads me to believe maybe the test didn't quite work right before.

### CODE REVIEW

**Comment by lvh** [comment]
jenkins, run integration tests please

**Comment by lvh** [comment]
jenkins, run integration tests please

**Comment by lvh** [comment]
jenkins please run integration tests

**Comment by manishtomar** [comment]
LGTM!

**Pull request merged**
