### PR TITLE
changes to check Nova counts after scaling

### PR DESCRIPTION
**Pull request by kivattik**

### CODE REVIEW

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
Expecting this to cause the tests to fail, which means it's doing it's job, since master is broken.  :)

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
Ok, these fail in the correct way.  This LGTM, wondering if I should merge this since that means all CI will fail until this bug is fixed (which I think it should, but I can be convinced otherwise)

**Comment by radix** [comment]
I think I'd rather not hold up other development while the bug is being fixed... is someone working on it?

**Comment by radix** [comment]
I just merged #1027, so we should be on our way.

**Pull request merged**
