### PR TITLE
Add `convergence` tags to a bunch of system integration tests

### PR DESCRIPTION
**Pull request by radix**
This adds 28 convergence='yes', and a bunch of convergence='error' tags on tests that I ran and which either didn't complete or failed.

### CODE REVIEW

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by manishtomar** [comment]
This is awesome! Great job @radix!!

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
jenkins please run unit tests

**Comment by radix** [comment]
jenkins passed the integration tests. I suspect that this unit test run is going to override the link to integration results. just wanted to comment for the record :)

original integration results: https://as-jenkins.rax.io/job/otter-pr-integration/87/

**Comment by manishtomar** [comment]
LGTM!

**Comment by radix** [comment]
thanks @manishtomar!

**Pull request merged**
