### PR TITLE
Mimic identity injection lib

### PR DESCRIPTION
**Pull request by cyli**
This will be needed for #1334.

This is dependent upon https://github.com/rackerlabs/mimic/pull/305 and also adding sequenced behavior to identity injections.

### CODE REVIEW

**Comment by cyli** [comment]
Closing this because actually the refactor to move some tiny same code is actually about as long as just copying and pasting.

**Comment by cyli** [comment]
Yeah ok, no, the refactor actually takes up more space than a copy-paste would.

**Comment by cyli** [comment]
Ok, thought of something else.

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by kivattik** [comment]
+1 LGTM :) And nice job on the tests.

**Comment by cyli** [comment]
jenkins please run integration tests

**Pull request merged**
