### PR TITLE
Delete bobby and maas policy integration tests

### PR DESCRIPTION
**Pull request by cyli**
Remove all the bobby tests and maas policy tests, since if there is going to be maas integration it is probably going to be implemented differently anyway.  (And if not, we can resurrect from git.)  This way there is less cloudcafe code to maintain.

The maas policy/bobby stuff in otter itself should probably also be removed, if this is removed.

### CODE REVIEW

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
[Integration tests failed as expected against master (the rcv3 tests)](https://as-jenkins.rax.io/job/dev-ci-integration-tests/81/console), but all others passed.

[Regular unit tests passed](https://as-jenkins.rax.io/job/otter-pr/2754/).

**Comment by manishtomar** [comment]
LGTM :) Yay deletion code!

I don't really understand about integration tests failing as expected but this is great.

**Comment by cyli** [comment]
@manishtomar @kivattik Added checking against nova to those rcv3 tests that should have failed, so they're failing against master now.

https://github.com/rackerlabs/otter/pull/1030 should hopefully fix them.

**Pull request merged**
