### PR TITLE
Change Cloud Identity to Identity

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by awfabian-rs** [comment]
Can one of the admins verify this patch?

**Comment by cyrichardson** [comment]
@awfabian-rs The Identity team is removing "Cloud" for the service in all external docs. InfoDev has been asked to provide PRs for all external docs for this change. Please let me know if I can help with the error in any way. If someone else can fix it and merge the PR that would be great. Thank you!

**Comment by awfabian-rs** [comment]
sorry for the delay. I meant to look at this one earlier.

**Comment by cyrichardson** [comment]
Thank you, @awfabian-rs!

**Pull request merged**
