### PR TITLE
Update get-credentials.rst to remove outdated screenshot

### PR DESCRIPTION
**Pull request by cyrichardson**
and point to a How-To article instead. Add note about cURL examples being for
reference only to auth-using-curl.rst and how-to-use-curl.rst

For issues: rackerlabs/docs-rackspace#282 and rackerlabs/docs-rackspace#261

### CODE REVIEW

**Comment by manishtomar** [comment]
Can one of the admins verify this patch?

**Comment by manishtomar** [comment]
Can one of the admins verify this patch?

**Comment by cyrichardson** [comment]
@manishtomar Hello! I worked with Margaret Eker. I don't have write access here, but wondered if you could review and merge this PR. I am doing this for all Public Cloud API docs based on customer feedback received. Thank you!

**Comment by manishtomar** [comment]
@cyrichardson Hello! Unfortunately I am not working with Rackspace anymore and don't have write access. The PR looks good though. I would've merged it :). I think @shawnashlee should be able to help you out here.

**Comment by cyrichardson** [comment]
@manishtomar Thank you for your note! Hopefully, @shawnashlee will merge it.

**Comment by cyrichardson** [comment]
Thank you @shawnashlee!

**Pull request merged**
