### PR TITLE
Update docs for launch_stack (rebased)

### PR DESCRIPTION
**Pull request by dragorosson**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-5e6b892545/docs/autoscale/v1/developer-guide/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-5937dca0fe/docs/autoscale/v1/developer-guide/)

**Comment by manishtomar** [comment]
Can one of the admins verify this patch?

**Comment by manishtomar** [comment]
Launching stacks is probably not going to be supported as development on Autoscale has been suspended. I am closing until I get any other notice.

**Pull request closed without merging**
