### PR TITLE
Remove docbook source files

### PR DESCRIPTION
**Pull request by meker12**
Clean up deprecated source files per
[Github issue #73](https://github.com/rackerlabs/docs-cloud-big-data/pull/73)

### CODE REVIEW

**Comment by manishtomar** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-930658872d/docs/autoscale/v1/developer-guide/)

**Comment by manishtomar** [comment]
Can one of the admins verify this patch?

**Comment by meker12** [comment]
@manishtomar This PR removes the docbook source files. Shouldn't create any merge conflicts because we haven't been updating any of the content in that folder.  Please merge if it looks OK.  Thanks!

**Comment by manishtomar** [comment]
Oh yes! Thank you for doing this! 👍 Will merge once build finishes :)

**Pull request merged**
