### PR TITLE
update twisted

### PR DESCRIPTION
**Pull request by manishtomar**
this includes new threadpool and logging system

### CODE REVIEW

**Comment by manishtomar** [comment]
jenkins please run integration tests

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-f511abf4ea/docs/autoscale/v1/developer-guide/)

**Comment by manishtomar** [comment]
jenkins please run integration tests

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-68f2ca9574/docs/autoscale/v1/developer-guide/)

**Comment by manishtomar** [comment]
jenkins please run integration tests

**Pull request merged**
