### PR TITLE
Split cloud_client

### PR DESCRIPTION
**Pull request by manishtomar**
`cloud_client.py` has functions for different services. This PR splits it into separate module and currently adds `cloudfeeds.py`. Will split other services in other PRs.

### CODE REVIEW

**Comment by manishtomar** [comment]
jenkins please run integration tests

**Comment by manishtomar** [comment]
@glyph review please?

**Comment by glyph** [comment]
@manishtomar - it's in the queue

**Comment by dragorosson** [comment]
LGTM

**Comment by manishtomar** [comment]
@dragorosson Thanks! @glyph you can safely take it out of your queue :)

**Comment by manishtomar** [comment]
FYI the integration tests [pass](https://as-jenkins.rax.io/job/otter-pr-integration/423/). Jenkins is having trouble updating the status here.

**Pull request merged**
