### PR TITLE
update otter for the txeffect split

### PR DESCRIPTION
**Pull request by radix**
effect.twisted was moved out of effect and into [txeffect](https://github.com/python-effect/txeffect) as of effect 0.1a18 and txeffect 0.1a1.

### CODE REVIEW

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
LGTM

**Pull request merged**
