### PR TITLE
Make convergence able to execute by putting TenantScope in the right place

### PR DESCRIPTION
**Pull request by radix**
When I did a last-minute refactor of execute_convergence in #1219, I inadvertently screwed up the wrapping of TenantScope around the effects that need to be wrapped. This completely broke convergence.

Clearly the tests were insufficient, so I've done two things:

- moved the wrapping of TenantScope to the exact piece of code that starts per-tenant processing of convergence: `converge_all_groups`
- improved the `converge_all_groups` test to be much more explicit about how `TenantScope` is being used, compared to the old test, so it truly verifies that all of the tenant-specific effects are being wrapped in the scope.

### CODE REVIEW

**Comment by lvh** [comment]
jenkins, please run integration tests

**Comment by lvh** [comment]
LGTM! I've asked Jenkins to look at integration tests too, although I suppose there's no reason to assume they'll suddenly start failing because of this PR.

**Comment by lvh** [comment]
Is it the comma? Is it random lag? Who knows?!

**Comment by lvh** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
good call @lvh, thanks :)

**Comment by radix** [comment]
Alright, merging cause jenkins passed. Thanks!

**Pull request merged**
