### PR TITLE
RCv3 refactor

### LINKED ISSUE #1839: RCv3 bulk add and delete retries forever
There should be a limit for retrying. The step should return FAILURE if the limit is reached causing the group to move to ERROR.

### PR DESCRIPTION
**Pull request by manishtomar**
Fixes #1839. This does lot of things:

- RCv3 functions in `cloud_client/rcv3.py` with better tests using sequence. Handles "Server unprocessable error" which was originally causing #1839. Earlier, it used to succeed on any unknown error that caused continuous retries. Now it fails on unknown errors and logs them. This should also shed light on #1815. 
- BulkAdd|Delete steps use the cloud_client functions
- Steps return RETRY instead of SUCCESS like CLB to update the cache in next cycle
- rcv3 request and response logging
- Moves log dispatcher to legacy dispatcher since it is needed by worker calling cloud_client rcv3

---
This change is [Reviewable](https://reviewable.io/reviews/rackerlabs/otter/1861)

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-3b811aba16/docs/autoscale/v1/developer-guide/). :bow:

**Comment by manishtomar** [comment]
jenkins please run integration tests

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-4ca74e6c8d/docs/autoscale/v1/developer-guide/).

**Comment by manishtomar** [comment]
jenkins please run integration tests

**Comment by manishtomar** [comment]
@glyph Could you review this? Unfortunately its pretty big change :/

**Comment by glyph** [comment]
@manishtomar wow, this is certainly... comprehensive.  I would be happy to do it but it'll probably take a couple of days to get to.  Friday?

**Comment by manishtomar** [comment]
> Friday?

Oh. Take your time. No hurries. I would normally take 3-4 days full to review such code even though I am familiar with the code.

**Comment by glyph** [comment]
Apologies in advance for the inevitably slightly messy review comments, but I'm going to use reviewable.io to keep track of how much of this code I've reviewed.

**Comment by glyph** [comment]
Looks like "friday" was optimistic :)

**Comment by glyph** [comment]
Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[otter/cloud_client/rcv3.py, line 18 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDsov32FtY0tK9r92A:-KEDsov32FtY0tK9r92B:-1135438542) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L18)):*
This is used in a couple of places, but its intention is far from clear.  A docstring would be helpful.

---

*[otter/cloud_client/rcv3.py, line 30 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDtDwt1UK8e09Nd961:-KEDtDwt1UK8e09Nd962:-79732410) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L30)):*
This is consistently referred to in the documentation, and in fact in the variable's name, as "node" -  http://docs.rcv3.apiary.io/#reference/load-balancer-pools/nodes-collection- why do you call it "collection" here?

---

*[otter/cloud_client/rcv3.py, line 50 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDuEXbPXjqUTRB-1Bo:-KEDuEXbPXjqUTRB-1Bp:708938032) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L50)):*
This regex is wrong; it's valid to use capital hex letters in UUIDs.  But, please don't match server names based on regex.

---

*[otter/cloud_client/rcv3.py, line 52 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDuQctxfjOxqTqCE3y:-KEDuQctxfjOxqTqCE3z:-1771660514) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L52)):*
Stability of its server naming convention is definitely not part of mimic's compatibility contract.

---

*[otter/cloud_client/rcv3.py, line 64 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDulfuI67EcbF78KrI:-KEDulfuI67EcbF78KrJ:-793198360) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L64)):*
These sub-patterns could easily be ".*" and the regex wouldn't change. So why all the elaborate UUID stuff above?

---

*[otter/cloud_client/rcv3.py, line 167 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDweD-ghWllQPa2z0c:-KEDweD-ghWllQPa2z0d:-1883974042) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L167)):*
(the comment in `_check_bulk_delete` also applies here)

---

*[otter/cloud_client/rcv3.py, line 232 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDvNs7iWFjp7owsB5x:-KEDvNs7iWFjp7owsB5y:1558172465) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L232)):*
Just a stylistic nitpick; when you have very-different-case if/else trees like this, especially in a for loop, you get namespace pollution; in this case, you might accidentally end up using a variable like `pair` `del_lb_id` outside of their appropriate suite, and you wouldn't notice.

For patterns like this you may want to consider a data-structure-interface oriented approach, for example, attaching each of these regexes to a class, and then doing something like this:

```python
for error in body["errors"]:
    for matchinator in _SERVER_NOT_A_MEMBER, _LB_INACTIVE, _LB_D_N_E, _SERVER_D_N_E:
        errors, non_members = matchinator.matchify(error, errors, non_members)
```

(hopefully that abbreviated example makes sense)

---

*[otter/test/cloud_client/test_init.py, line 149 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDx8DaU2l6U6WtI_87:-KEDx8DaU2l6U6WtI_88:-2018354488) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/test/cloud_client/test_init.py#L149)):*
Just curious: why not unconditionally include `request_body` and make it be `None` sometimes?  Or, better yet, the empty string?  My understanding is that elasticsearch would be a lot happier with `""` here, because it's changing types of field names that cause issues.

---

*[otter/test/cloud_client/test_rcv3.py, line 80 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDxZ1MBKrxjiaiMpMx:-KEDxZ1MBKrxjiaiMpMy:-1184077358) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/test/cloud_client/test_rcv3.py#L80)):*
It feels to me like testing the regexes directly is overkill; you're testing the error translation here, and it's not like the regexes themselves are exported library functionality (they go to a lot of trouble to include copious numbers of prefixed underscores to illustrate as aggressively as possible that they're *not* exported, even though otter isn't even a library!) and it's the error translation you really care about; these regexes are an implementation detail, and a highly unfortunate one at that.  Deleting these tests would also make the code quite a bit smaller :).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rackerlabs/otter/1861)*

**Comment by glyph** [comment]
Hopefully those comments were useful.  As far as I can tell reviewing the changes, this does have the desired effect, but there's a ''lot'' of code here and it's somewhat difficult to tell without fully absorbing the entire old implementation.

I am unhappy about the regexes, but I think they could be addressed in a follow-up change, because that's a code-cleanliness and future-proofing issue, not a behavioral one; as the dependencies all stand now, it behaves correctly.

**Comment by manishtomar** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[otter/cloud_client/rcv3.py, line 30 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDtDwt1UK8e09Nd961:-KEE6KjA97yTklQ-VlIG:-1056240303) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L30)):*
Sorry where is "collection" used? The name is`lb_node_pairs` right?

---

*[otter/cloud_client/rcv3.py, line 64 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDulfuI67EcbF78KrI:-KEFBAtDs5x4nb3Ui3pD:990522518) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L64)):*
Laziness :( Just wanted to get the PR up. I think you are right. Will change it to `.*`

---

*[otter/cloud_client/rcv3.py, line 232 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDvNs7iWFjp7owsB5x:-KEE78JeyWSdZL_tmSlC:-1781303219) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L232)):*
I wanted to have something like this but couldn't come up with decent implementation primarily because the behavior is different in just one of the case (NOT_A_MEMBER). It seemed over-engineering at some point. Let me revisit it. However, just to be clear I might not spend much time on it :)

---

*[otter/test/cloud_client/test_init.py, line 149 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDx8DaU2l6U6WtI_87:-KEF8cvfTlNSWdnTkh8_:1805440562) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/test/cloud_client/test_init.py#L149)):*
Hmm. I like the idea of unconditionally setting `request_body=""`. However, is there a difference between empty request body vs `None` request body? For example is it ok set empty string for a GET request?

---

*[otter/test/cloud_client/test_rcv3.py, line 80 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDxZ1MBKrxjiaiMpMx:-KEF9KTCvnIHbEbW0JR0:-46457294) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/test/cloud_client/test_rcv3.py#L80)):*
I just copied them from original source. Sounds like a good idea to remove them. Will do.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rackerlabs/otter/1861)*

**Comment by glyph** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[otter/cloud_client/rcv3.py, line 30 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDtDwt1UK8e09Nd961:-KEHrINn9oVqOot9jTFH:-263515082) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L30)):*
Sorry.  *connection*.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rackerlabs/otter/1861)*

**Comment by manishtomar** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[otter/cloud_client/rcv3.py, line 30 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDtDwt1UK8e09Nd961:-KEHuMqIsYL_OGn9ONF9:-470418589) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L30)):*
Hmm. The (lb_id, node_id) combination is a _connection_. A connection between the two is created or deleted. Looks like rcv3 doc refers a `node` to be combination of lb_id and server_id whereas this code correlates node to be server :confused:. Ideally, this API should replace node with server everywhere and use `node` to refer to `(lb_id, server_id)` tuple. Would it be ok to do it in another PR?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rackerlabs/otter/1861)*

**Comment by glyph** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[otter/cloud_client/rcv3.py, line 30 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDtDwt1UK8e09Nd961:-KEIv04S_lD8yl25f36y:1500665414) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L30)):*
Yes, it's a minor readability thing and shouldn't block the merge, but it would be nice to capture so it doesn't get forgotten about.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rackerlabs/otter/1861)*

**Comment by glyph** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[otter/test/cloud_client/test_init.py, line 149 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDx8DaU2l6U6WtI_87:-KEIvHilPb55F8lBQi-C:-416153584) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/test/cloud_client/test_init.py#L149)):*
Protocol-wise, no.  GET isn't defined to take an entity-body (although the spec is somewhat vague on the specifics: https://pretty-rfc.herokuapp.com/RFC2616#GET ) but as far as the *logs* are concerned there's no difference.  It's not like a response body on a HEAD request where content-length takes on a different meaning; the request body will just be parsed and discarded.

If you really care about the distinction, I would recommend adding a separate "body_present" boolean field; this would make it a lot easier to query for in elasticsearch anyway.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rackerlabs/otter/1861)*

**Comment by manishtomar** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[otter/cloud_client/rcv3.py, line 52 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDuQctxfjOxqTqCE3y:-KEJ3Lo0KyKBF-AorAPh:-1052169303) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L52)):*
It would be nice to have mimic's contract documented. AFAIU mimic is supposed to provide same behavior as openstack and that [documents](http://developer.openstack.org/api-ref-compute-v2.1.html#createServer) server ID to be UUID. I realize that depending on it _here_ is incorrect but it seems inconsistent with what a client will expect. In any case, I'll be removing UUID parsing and we can continue this discussion elsewhere if needed.

---

*[otter/test/cloud_client/test_init.py, line 149 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDx8DaU2l6U6WtI_87:-KEJ28L5m57AlF-MhQnV:-808356016) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/test/cloud_client/test_init.py#L149)):*
OK cool. Will set empty string. Thanks!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rackerlabs/otter/1861)*

**Comment by glyph** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[otter/cloud_client/rcv3.py, line 52 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDuQctxfjOxqTqCE3y:-KEJ52poMPwq5NRIDT2c:-833648115) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L52)):*
That documentation reference wins - file a bug on Mimic to start using UUIDs, and reference it there :).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rackerlabs/otter/1861)*

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-d5c8a1817d/docs/autoscale/v1/developer-guide/).

**Comment by manishtomar** [comment]
jenkins please run integration tests

**Comment by manishtomar** [comment]
Review status: 8 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[otter/cloud_client/rcv3.py, line 18 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDsov32FtY0tK9r92A:-KEc942E4oCObq4ju1dX:-499146009) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L18)):*
Done.

---

*[otter/cloud_client/rcv3.py, line 50 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDuEXbPXjqUTRB-1Bo:-KEc92oc2lZXvk7fdnM5:-499146009) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L50)):*
Done.

---

*[otter/cloud_client/rcv3.py, line 52 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDuQctxfjOxqTqCE3y:-KEc8qY_hf4zHFYR6nch:815435684) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L52)):*
https://github.com/rackerlabs/mimic/issues/566

---

*[otter/cloud_client/rcv3.py, line 232 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDvNs7iWFjp7owsB5x:-KEcEkld6kxNaM5gRXLP:1086426442) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L232)):*
Would you mind leaving this as it is? I've done rest of the times.

---

*[otter/test/cloud_client/test_init.py, line 149 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDx8DaU2l6U6WtI_87:-KEc8wE-j_sQsvN9nkRA:-499146009) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/test/cloud_client/test_init.py#L149)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rackerlabs/otter/1861)*

**Comment by glyph** [comment]
Review status: 8 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[otter/cloud_client/rcv3.py, line 232 \[r2\]](https://reviewable.io:443/reviews/rackerlabs/otter/1861#-KEDvNs7iWFjp7owsB5x:-KEm2eSK6RAhZBoHr9HB:-107951484) ([raw file](https://github.com/rackerlabs/otter/blob/ce88181aaff546ec3e4f8193467f66f0e6f9823f/otter/cloud_client/rcv3.py#L232)):*
Sure. I should have said that this was also something that could be addressed in a follow up (or not at all, it's mostly for your consideration).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rackerlabs/otter/1861)*

**Pull request merged**
