### PR TITLE
Microseconds in timestamps

### LINKED ISSUE #1393: Timestamps for comparing age of servers has insufficient precision
Some of the integration tests sometimes fail because autoscale deletes the wrong servers (the newest servers instead of the oldest servers), because if the created timestamps are too close to each other, autoscale thinks they were created at the same time.

One test that failed was `autoscale_cloudroast.test_repo.autoscale.system.group.test_system_launch_config.LaunchConfigTests.test_update_launchconfig_group_maxentities`.  There were two servers.  Here are the created times from mimic:

- `2015-05-01T04:51:12.078580Z`
- `2015-05-01T04:51:12.906496Z`

Autoscale interpreted both these creation times as the following epoch time: `1430455872`.

So it arbitrarily deleted one, which happened to be the newest one.

Here are the two server blobs from mimic:

```{"server": {"status": "ACTIVE", "updated": "2015-05-01T04:51:12.078580Z", "OS-EXT-STS:task_state": null, "user_id": "170454", "addresses": {"public": [{"version": 4, "addr": "198.101.241.236"}, {"version": 6, "addr": "2001:4800:780e:0510:d87b:9cbc:ff04:513a"}], "private": [{"version": 4, "addr": "10.180.50.238"}]}, "links": [{"href": "http://192.168.7.1:8900/mimicking/NovaApi-357340/ORD/v2/000000/servers/test-server906471524-id-906471524", "rel": "self"}, {"href": "http://192.168.7.1:8900/mimicking/NovaApi-357340/ORD/000000/servers/test-server906471524-id-906471524", "rel": "bookmark"}], "created": "2015-05-01T04:51:12.078580Z", "key_name": null, "image": {"id": "0d589460-f177-4b0f-81c1-8ab8903ac7d8", "links": [{"href": "http://192.168.7.1:8900/mimicking/NovaApi-357340/ORD/000000/images/2", "rel": "bookmark"}]}, "OS-DCF:diskConfig": "AUTO", "id": "test-server906471524-id-906471524", "accessIPv4": "198.101.241.238", "accessIPv6": "2001:4800:780e:0510:d87b:9cbc:ff04:513a", "OS-EXT-STS:vm_state": "ACTIVE", "tenant_id": "000000", "progress": 100, "OS-EXT-STS:power_state": 1, "metadata": {"rax:autoscale:group:id": "7423fadd-44e4-48bf-ba4d-9c31aad3f84e", "build_config": "core", "rax:auto_scaling_group_id": "7423fadd-44e4-48bf-ba4d-9c31aad3f84e"}, "flavor": {"id": "2", "links": [{"href": "http://192.168.7.1:8900/mimicking/NovaApi-357340/ORD/000000/flavors/2", "rel": "bookmark"}]}, "hostId": "33ccb6c82f3625748b6f2338f54d8e9df07cc583251e001355569056", "name": "test_sg_bhv_srv762530-as194a197e"}}```

```{"server": {"status": "ACTIVE", "updated": "2015-05-01T04:51:12.906496Z", "OS-EXT-STS:task_state": null, "user_id": "170454", "addresses": {"public": [{"version": 4, "addr": "198.101.241.19"}, {"version": 6, "addr": "2001:4800:780e:0510:d87b:9cbc:ff04:513a"}], "private": [{"version": 4, "addr": "10.180.181.183"}]}, "links": [{"href": "http://192.168.7.1:8900/mimicking/NovaApi-357340/ORD/v2/000000/servers/test-server1391948842-id-1391948842", "rel": "self"}, {"href": "http://192.168.7.1:8900/mimicking/NovaApi-357340/ORD/000000/servers/test-server1391948842-id-1391948842", "rel": "bookmark"}], "created": "2015-05-01T04:51:12.906496Z", "key_name": null, "image": {"id": "92ac9889-2ede-4633-ab39-25560436d83a", "links": [{"href": "http://192.168.7.1:8900/mimicking/NovaApi-357340/ORD/000000/images/3", "rel": "bookmark"}]}, "OS-DCF:diskConfig": "AUTO", "id": "test-server1391948842-id-1391948842", "accessIPv4": "198.101.241.238", "accessIPv6": "2001:4800:780e:0510:d87b:9cbc:ff04:513a", "OS-EXT-STS:vm_state": "ACTIVE", "tenant_id": "000000", "progress": 100, "OS-EXT-STS:power_state": 1, "metadata": {"rax:autoscale:group:id": "7423fadd-44e4-48bf-ba4d-9c31aad3f84e", "rax:auto_scaling_group_id": "7423fadd-44e4-48bf-ba4d-9c31aad3f84e"}, "flavor": {"id": "3", "links": [{"href": "http://192.168.7.1:8900/mimicking/NovaApi-357340/ORD/000000/flavors/3", "rel": "bookmark"}]}, "hostId": "33ccb6c82f3625748b6f2338f54d8e9df07cc583251e001355569056", "name": "updlc_config435733-asbcaae47f"}}```

And here is the convergence log from otter:

```
{
  "servers": [
    "<NovaServer(id=u'test-server906471524-id-906471524', state=<ServerState=ACTIVE>, created=1430455872, image_id=u'0d589460-f177-4b0f-81c1-8ab8903ac7d8', flavor_id=u'2', links=pvector([pmap({u'href': u'http://localhost:8900/mimicking/NovaApi-357340/ORD/v2/000000/servers/test-server906471524-id-906471524', u'rel': u'self'}), pmap({u'href': u'http://localhost:8900/mimicking/NovaApi-357340/ORD/000000/servers/test-server906471524-id-906471524', u'rel': u'bookmark'})]), desired_lbs=pset([]), servicenet_address=u'10.180.50.238')>", 
    "<NovaServer(id=u'test-server1391948842-id-1391948842', state=<ServerState=ACTIVE>, created=1430455872, image_id=u'92ac9889-2ede-4633-ab39-25560436d83a', flavor_id=u'3', links=pvector([pmap({u'href': u'http://localhost:8900/mimicking/NovaApi-357340/ORD/v2/000000/servers/test-server1391948842-id-1391948842', u'rel': u'self'}), pmap({u'href': u'http://localhost:8900/mimicking/NovaApi-357340/ORD/000000/servers/test-server1391948842-id-1391948842', u'rel': u'bookmark'})]), desired_lbs=pset([]), servicenet_address=u'10.180.181.183')>"
  ], 
  "otter_facility": "otter", 
  "level": 6, 
  "lb_nodes": [], 
  "@timestamp": "2015-05-01T04:51:20.562456", 
  "otter_msg_type": "execute-convergence", 
  "scaling_group_id": "7423fadd-44e4-48bf-ba4d-9c31aad3f84e", 
  "desired": "<DesiredGroupState(server_config=pmap({'server': pmap({u'flavorRef': u'3', u'name': u'updlc_config435733', u'imageRef': u'92ac9889-2ede-4633-ab39-25560436d83a', 'metadata': pmap({'rax:autoscale:group:id': u'7423fadd-44e4-48bf-ba4d-9c31aad3f84e', 'rax:auto_scaling_group_id': u'7423fadd-44e4-48bf-ba4d-9c31aad3f84e'})})}), capacity=1, desired_lbs=pset([]), draining_timeout=0.0)>", 
  "host": "api1.preprod.ord.as.rax.io", 
  "steps": [
    "<DeleteServer(server_id=u'test-server1391948842-id-1391948842')>"
  ], 
  "tenant_id": "000000", 
  "active": [
    "<NovaServer(id=u'test-server906471524-id-906471524', state=<ServerState=ACTIVE>, created=1430455872, image_id=u'0d589460-f177-4b0f-81c1-8ab8903ac7d8', flavor_id=u'2', links=pvector([pmap({u'href': u'http://localhost:8900/mimicking/NovaApi-357340/ORD/v2/000000/servers/test-server906471524-id-906471524', u'rel': u'self'}), pmap({u'href': u'http://localhost:8900/mimicking/NovaApi-357340/ORD/000000/servers/test-server906471524-id-906471524', u'rel': u'bookmark'})]), desired_lbs=pset([]), servicenet_address=u'10.180.50.238')>", 
    "<NovaServer(id=u'test-server1391948842-id-1391948842', state=<ServerState=ACTIVE>, created=1430455872, image_id=u'92ac9889-2ede-4633-ab39-25560436d83a', flavor_id=u'3', links=pvector([pmap({u'href': u'http://localhost:8900/mimicking/NovaApi-357340/ORD/v2/000000/servers/test-server1391948842-id-1391948842', u'rel': u'self'}), pmap({u'href': u'http://localhost:8900/mimicking/NovaApi-357340/ORD/000000/servers/test-server1391948842-id-1391948842', u'rel': u'bookmark'})]), desired_lbs=pset([]), servicenet_address=u'10.180.181.183')>"
  ], 
  "message": "Executing convergence", 
  "now": 1430455880.56203, 
  "@version": 1, 
  "otter_service": "converger"
}
```

### PR DESCRIPTION
**Pull request by cyli**
This gives us more precision when determining which server to delete.

Fixes #1393.

### CODE REVIEW

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
LGTM! :)

**Comment by radix** [comment]
(and thanks for updating the ParseError exception thingy)

**Pull request merged**
