### PR TITLE
Adding multi-factor authentication references

### PR DESCRIPTION
**Pull request by meker12**
about other authentication methods, including multi-factor
authentication.

### CODE REVIEW

**Comment by stretchservers** [comment]
Can one of the admins verify this patch?

**Comment by stretchservers** [comment]
Can one of the admins verify this patch?

**Comment by cyli** [comment]
ok to test

**Comment by stretchservers** [comment]
Can one of the admins verify this patch?

**Comment by lvh** [comment]
LGTM, thanks!

**Pull request merged**
