### PR TITLE
Small fix to CF dispatcher

### PR DESCRIPTION
**Pull request by cyli**
Cloudfeeds was calling `get_full_dispatcher` with the wrong number of arguments, but it really only needs to make `cloud_client` calls, so switch dispatchers to `get_legacy_dispatcher`.

Wondering if we should rename `get_legacy_dispatcher`, since it's just a dispatcher that makes cloud client calls in addition to the simple dispatcher?

### CODE REVIEW

**Comment by manishtomar** [comment]
> Wondering if we should rename get_legacy_dispatcher, since it's just a dispatcher that makes cloud client calls in addition to the simple dispatcher?

How about `get_cloud_client_dispatcher`? But that should be separate PR if you decide to do it :).

**Comment by cyli** [comment]
> How about get_cloud_client_dispatcher? But that should be separate PR if you decide to do it :).

There already is one.  :|  `get_legacy_dispatcher` is the composition of that and `get_simple_dispatcher`, otherwise I would have just gone and renamed.

**Comment by manishtomar** [comment]
LGTM!

**Comment by cyli** [comment]
Thanks!

**Pull request merged**
