### PR TITLE
running trial without subprocesses

### PR DESCRIPTION
**Pull request by manishtomar**
This fixes coverage and in effect coveralls as it cannot track subprocess without some [changes](http://nedbatchelder.com/code/coverage/subprocess.html)

### CODE REVIEW

**Comment by radix** [comment]
this only needs to change for the `coverage` target, right? can you make it so the normal test runs still use -j but only coverage doesn't?

**Comment by manishtomar** [comment]
Yeah. Can do that. Will do.

**Comment by lvh** [comment]
LGTM assuming Travis is happy

**Comment by radix** [comment]
woo! 98%!

**Pull request merged**
