### PR TITLE
RCv3 bulk add success semantics

### PR DESCRIPTION
**Pull request by lvh**
This adds support for inactive LBs and nonexistent LBs. In both cases, the request is set to failure. (It's possible that we get to retry these failed groups later, but for now I think failure is the most correct thing that describes what happened).

This refs #955, but doesn't resolve it yet. There's still the matter of invalid cloud servers and "unprocessable" cloud servers.

### CODE REVIEW

**Comment by lvh** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
Just to make sure I remember, does the failure step means wedge the group and put into error state?

**Comment by lvh** [comment]
Yes, for now.

**Comment by cyli** [comment]
Non-blocking nitpick - do we want to say which server needed which load balancer?  Users might get confused if we eventually log those errors, if it's a load balancer that's no longer on their launch config.

**Comment by lvh** [comment]
Yeah, that's a great idea. Crossed my mind while writing it, no idea why I forgot about it. I've already been building on this branch for something else; since you mentioned it's non-blocking, I'll file a ticket for that and do it next?

**Comment by cyli** [comment]
Sounds good.  This LGTM if the integration tests pass - for some reason it's not running :|

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by lvh** [comment]
Jenkins has basically stopped listening to me

**Comment by cyli** [comment]
jenkins doesn't listen to anyone at this point :|

**Comment by cyli** [comment]
oh there it goes

**Comment by lvh** [comment]
(#1098 is that ticket)

**Pull request merged**
