### PR TITLE
Support RCv3 out-of-band delete

### LINKED ISSUE #820: Handle nodes being deleted out-of-band for RCv3
Suppose node `A` is attached to load balancer `B`. Node `A` is deleted out-of-band. Otter scales down, and wants to get rid of `A` (i.e. remove it from its load balancer and delete the node). The load balancer removal step errors out. In the CLB code path, this is still considered a success. 

For the Rackers, this is [AS-425](https://jira.rax.io/browse/AS-425).

### PR DESCRIPTION
**Pull request by lvh**
Closes #820.

This is currently blocked on RCv3 getting back to us re: atomicity semantics of bulk operations.

### CODE REVIEW

**Comment by lvh** [comment]
So, according to RCv3, requests are validated *before* attempting to execute them, and bulk requests are atomic. That's unfortunate, because it might mean that the only way to recover from this mess is "whatever, converge again".

**Comment by cyli** [comment]
@lvh Or retry one particular add with all the problematic servers removed.  It's probably fine to wait for the next converge cycle.

**Comment by lvh** [comment]
Right, but currently we have no way of specifying "retry this *other* effect instead", and the effect doesn't know if this is attempt number 1 or number 37, so...

**Comment by radix** [comment]
Yes you do: add an error callback that calls service_request and returns the result. You can even maintain a counter as a parameter you pass from callback to callback.

**Comment by lvh** [comment]
Sorry, I keep forgetting that parametrization bit :)

**Comment by lvh** [comment]
It appears the real resolution of this issue is going to be "perform some other effects". I'll update the parent ticket and close this PR for now.

**Pull request closed without merging**
