### PR TITLE
Fix table format error

### PR DESCRIPTION
**Pull request by meker12**
Also removed unnecessary blank lines

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-82028d30da/docs/autoscale/v1/developer-guide/)

**Comment by manishtomar** [comment]
Can one of the admins verify this patch?

**Comment by manishtomar** [comment]
Can one of the admins verify this patch?

**Comment by manishtomar** [comment]
LGTM

**Pull request merged**
