### PR TITLE
Serialize convergence gathering

### PR DESCRIPTION
**Pull request by dragorosson**
This is preparation code for the addition of launch_server.

### CODE REVIEW

**Comment by stretchservers** [comment]
Can one of the admins verify this patch?

**Comment by stretchservers** [comment]
Can one of the admins verify this patch?

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
Nice small change. (smaller than I expected! I guess the tests were slightly better factored than I expected...)

**Pull request merged**
