### PR TITLE
Always converge even if delta is zero

### PR DESCRIPTION
**Pull request by cyli**
For the explanation given in the comment.

### CODE REVIEW

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by radix** [comment]
LGTM. Sorry you had to deal with this!

**Comment by cyli** [comment]
Sorry I didn't run integration tests again after the last change.  :|  Didn't realize that change would break everything.

**Comment by cyli** [comment]
jenkins please run integration tests

**Comment by cyli** [comment]
jenkins please run integration tests

**Pull request merged**
