### PR TITLE
Parallel trial unit test runs

### PR DESCRIPTION
**Pull request by lvh**
This should shave some time off of our PR builds.

### CODE REVIEW

**Comment by lvh** [comment]
Looks like this is failing because unitgration being weird. Fortunately, #1011 is around to get rid of it; once that's merged, we'll merge this forward, and hopefully it'll be better and we'll be on our way to significantly faster tests.

**Comment by cyli** [comment]
`Build step 'Publish JUnit test result report' changed build result to UNSTABLE`  :|

One more time.

jenkins retest this please

**Comment by lvh** [comment]
Failure's consistent at least ;)

**Comment by lvh** [comment]
Weird. Works fine for me; I don't know what it doesn't like about that JUnit XML :/

**Comment by lvh** [comment]
retest this please

**Comment by lvh** [comment]
It claims that it can't read the resulting XML file, though: https://as-jenkins.rax.io/job/otter-pr/2716/testReport/test-report/xml/_init_/

**Comment by cyli** [comment]
:|  retest this please

**Comment by lvh** [comment]
@cyli YESSSSSS

**Comment by cyli** [comment]
YAY!!!   LGTM.  (looks like doesn't help jenkins all that much, but might help folks locally :D)

**Pull request merged**
