### PR TITLE
Return resources in dict instead of tuple

### PR DESCRIPTION
**Pull request by dragorosson**

### CODE REVIEW

**Comment by stretchservers** [comment]
Can one of the admins verify this patch?

**Comment by stretchservers** [comment]
Can one of the admins verify this patch?

**Comment by radix** [comment]
jenkins please run integration tests

**Comment by manishtomar** [comment]
jenkins please run integration tests

**Comment by dragorosson** [comment]
Merge?

**Comment by radix** [comment]
LGTM! :)

**Pull request merged**
