### PR TITLE
trying codecov

### PR DESCRIPTION
**Pull request by manishtomar**
Switching to codecov as it provides better reporting.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-f001b88391/docs/autoscale/v1/developer-guide/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-add09483de/docs/autoscale/v1/developer-guide/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-db54cd1d31/docs/autoscale/v1/developer-guide/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-1620750b73/docs/autoscale/v1/developer-guide/). :bow:

**Comment by wirehead** [comment]
<3 Codecov.

(I still use Otter test coverage as a "See, we delivered a product on a tight deadline and look at the test coverage" example :) )

**Comment by manishtomar** [comment]
@wirehead Hi! Great to see you 😃 And thanks for the compliment :)

**Pull request merged**
