### PR TITLE
Lint fixes

### PR DESCRIPTION
**Pull request by lvh**
It's reverts all the way down

### CODE REVIEW

**Comment by cyli** [comment]
Eh, looking at all changes it probably would have been a LGTM anyway?  Not sure if we want to just leave it and close this PR.  Up to you.

**Comment by lvh** [comment]
This *unreverts* the reverts. I already reverted them on master :)

**Comment by lvh** [comment]
One of the commits didn't get re-reverted, so I added it again.

**Comment by cyli** [comment]
Bleh, I misread.  LGTM.  Thanks for fixing!  This is breaking all my PRs.  :)

**Pull request merged**
