### PR TITLE
Change KC link to how-to

### PR DESCRIPTION
**Pull request by meker12**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-e7dbea3322/docs/autoscale/v1/developer-guide/)

**Comment by manishtomar** [comment]
Can one of the admins verify this patch?

**Comment by manishtomar** [comment]
Can one of the admins verify this patch?

**Comment by manishtomar** [comment]
LGTM

**Pull request merged**
